### ISSUE TITLE
CODE is empty,please get the code first.

### ISSUE THREAD

**Issue by tonywangcn** [skyleft/Python-Youku-Uploader#1]
Found 1 videos,start uploading now.
CODE is empty,please get the code first.
CODE应该填什么呢？

**Comment by xiuliren** [comment]
same error and question here!

**Comment by skyleft** [comment]
@tonywangcn @jingpengw 
现在的情况 code可以GET一下这个url获得 https://openapi.youku.com/v2/oauth2/authorize?client_id=xxxxxxx&response_type=code&redirect_uri=xxxxxxxxx
当时code已经有了 就没写这块
具体参考http://doc.open.youku.com/?docid=387
